"""Bake extracted Crimsonland Classic sprites into the Godot project (M3).

Reads the PNG sheets produced by `crimson extract <game_dir> artifacts/assets`
and stages the ones the VR frontend renders into
`crimson-vr/godot/assets/sprites/` (gitignored — original art is never
committed, PLAN §10), alongside a JSON manifest describing how each entity type
maps to a sheet + frame. The manifest holds only factual layout metadata
(sheet name, grid, frame index, pivot), not asset-derived art.

Slice 1 (static frames): creatures + player as single representative frames.
Sheets are 8x8 grids (creature_render_type, src/crimson/creatures/anim.py); the
frame index within a sheet is chosen from anim_phase at render time — deferred
to slice 2, so this bakes frame 0 as the static pose (orientation still comes
from the entity heading, applied by the renderer).

Usage:
    uv run crimson-vr/tools/bake_assets.py [assets_dir] [out_dir]
      assets_dir default: artifacts/assets
      out_dir     default: crimson-vr/godot/assets/sprites
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

# Creature type_id -> sheet (src/crimson/creatures/spawn_ids.py CreatureTypeId).
CREATURE_SHEETS: dict[int, str] = {
    0: "zombie.png",
    1: "lizard.png",
    2: "alien.png",
    3: "spider_sp1.png",
    4: "spider_sp2.png",
    5: "trooper.png",
}
CREATURE_GRID = 8  # 8x8 atlas (creature_render_type)

# Sheets to stage: (source-relative-path, dest-name).
GAME = "crimson/game"


def main() -> None:
    assets_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("artifacts/assets")
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("crimson-vr/godot/assets/sprites")
    out_dir.mkdir(parents=True, exist_ok=True)

    needed = set(CREATURE_SHEETS.values()) | {"bodyset.png", "projs.png", "bonuses.png"}
    staged: dict[str, list[int]] = {}
    for name in sorted(needed):
        src = assets_dir / GAME / name
        if not src.exists():
            print(f"WARN missing sheet: {src}")
            continue
        shutil.copy2(src, out_dir / name)
        # Record pixel size so the manifest is self-describing for the renderer.
        from PIL import Image

        with Image.open(src) as im:
            staged[name] = list(im.size)

    manifest = {
        "note": "Generated by crimson-vr/tools/bake_assets.py from user-supplied "
        "Crimsonland Classic assets. Layout metadata only; no art is committed.",
        "sheets": {
            name: {"size": size, "grid": CREATURE_GRID if name in CREATURE_SHEETS.values() else None}
            for name, size in staged.items()
        },
        "creatures": {
            str(type_id): {"sheet": sheet, "grid": CREATURE_GRID, "frame": 0, "pivot": [0.5, 0.5]}
            for type_id, sheet in CREATURE_SHEETS.items()
            if sheet in staged
        },
        # Player is drawn from trooper.png (8x8), same sheet as the trooper
        # creature (src/crimson/render/world/trooper.py). torso_frame = leg_frame
        # + 16; static torso pose is frame 16, rotated by aim direction. (bodyset
        # is corpse decals, not the living player.)
        "player": {"sheet": "trooper.png", "grid": 8, "frame": 16, "pivot": [0.5, 0.5]}
        if "trooper.png" in staged
        else None,
    }

    manifest_path = out_dir / "sprite_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"staged {len(staged)} sheets -> {out_dir}")
    print(f"wrote {manifest_path}")


if __name__ == "__main__":
    main()
