"""Bake extracted Crimsonland Classic sprites into the Godot project (M3).

Reads the PNG sheets produced by `crimson extract <game_dir> artifacts/assets`
and stages the ones the VR frontend renders into
`crimson-vr/godot/assets/sprites/` (gitignored — original art is never
committed, PLAN §10), alongside a JSON manifest describing how each entity type
maps to a sheet + frame. The manifest holds only factual layout metadata
(sheet name, grid, frame index, pivot), not asset-derived art.

Sheets are 8x8 grids (creature_render_type, src/crimson/creatures/anim.py). The
manifest carries each creature's animation layout (base_frame, mirror); the
renderer selects the live frame per instance from the snapshot's anim_phase +
flags (CreatureAnim.SelectFrame, slice 2). Orientation comes from the entity
heading, applied by the renderer. The player is still a single static torso
frame (leg animation needs a move-phase ABI field; deferred).

Usage:
    uv run crimson-vr/tools/bake_assets.py [assets_dir] [out_dir]
      assets_dir default: artifacts/assets
      out_dir     default: crimson-vr/godot/assets/sprites
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

# Creature type_id -> sheet (src/crimson/creatures/spawn_ids.py CreatureTypeId).
CREATURE_SHEETS: dict[int, str] = {
    0: "zombie.png",
    1: "lizard.png",
    2: "alien.png",
    3: "spider_sp1.png",
    4: "spider_sp2.png",
    5: "trooper.png",
}
CREATURE_GRID = 8  # 8x8 atlas (creature_render_type)

# Per-type animation layout (src/crimson/sim/world_defs.py CREATURE_ANIM):
# base frame index + whether the long-strip walk cycle mirror-folds. The live
# anim_phase + runtime flags (both in the ABI snapshot) pick the actual frame at
# render time via CreatureAnim.SelectFrame (a port of creature_anim_select_frame).
# anim_rate is a sim-side quantity (it advances anim_phase) and is not needed by
# the frontend. type_id -> (base_frame, mirror).
CREATURE_ANIM: dict[int, tuple[int, bool]] = {
    0: (0x20, False),  # zombie
    1: (0x10, True),   # lizard
    2: (0x20, False),  # alien
    3: (0x10, True),   # spider_sp1
    4: (0x10, True),   # spider_sp2
    5: (0x00, False),  # trooper
}

# Draw-order priority per type (higher = drawn on top), matching the original's
# fixed creature draw order (_NATIVE_CREATURE_SPRITE_DRAW_ORDER, bottom->top):
# ZOMBIE, SPIDER_SP1, SPIDER_SP2, ALIEN, LIZARD. The game does no per-instance
# Y-sort; within a type it's pool order. Trooper isn't in the native list, so it
# gets a mid value.
CREATURE_PRIORITY: dict[int, int] = {
    0: 6,   # zombie (bottom)
    3: 7,   # spider_sp1
    4: 8,   # spider_sp2
    5: 9,   # trooper (not in native pass)
    2: 9,   # alien
    1: 10,  # lizard (top)
}
PLAYER_PRIORITY = 15  # above creatures, below projectiles/bonuses (native pass order)

# Sheets to stage: (source-relative-path, dest-name).
GAME = "crimson/game"


def main() -> None:
    assets_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("artifacts/assets")
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("crimson-vr/godot/assets/sprites")
    out_dir.mkdir(parents=True, exist_ok=True)

    needed = set(CREATURE_SHEETS.values()) | {"bodyset.png", "projs.png", "bonuses.png"}
    staged: dict[str, list[int]] = {}
    for name in sorted(needed):
        src = assets_dir / GAME / name
        if not src.exists():
            print(f"WARN missing sheet: {src}")
            continue
        shutil.copy2(src, out_dir / name)
        # Record pixel size so the manifest is self-describing for the renderer.
        from PIL import Image

        with Image.open(src) as im:
            staged[name] = list(im.size)

    manifest = {
        "note": "Generated by crimson-vr/tools/bake_assets.py from user-supplied "
        "Crimsonland Classic assets. Layout metadata only; no art is committed.",
        "sheets": {
            name: {"size": size, "grid": CREATURE_GRID if name in CREATURE_SHEETS.values() else None}
            for name, size in staged.items()
        },
        # offset_deg corrects each sheet's baked art facing relative to the sim
        # heading. Creature sheets are drawn 90 deg CW of the trooper torso, so
        # rotate them -90 (validated in-headset against the debug needle).
        "creatures": {
            str(type_id): {
                "sheet": sheet, "grid": CREATURE_GRID,
                # frame is the static fallback (used only if animation is off or
                # the layer draws colored quads); base_frame + mirror drive the
                # animated per-instance frame selection.
                "frame": CREATURE_ANIM.get(type_id, (0, False))[0],
                "base_frame": CREATURE_ANIM.get(type_id, (0, False))[0],
                "mirror": CREATURE_ANIM.get(type_id, (0, False))[1],
                "pivot": [0.5, 0.5], "offset_deg": -90.0,
                "priority": CREATURE_PRIORITY.get(type_id, 8),
            }
            for type_id, sheet in CREATURE_SHEETS.items()
            if sheet in staged
        },
        # Player is drawn from trooper.png (8x8), same sheet as the trooper
        # creature (src/crimson/render/world/trooper.py). torso_frame = leg_frame
        # + 16; static torso pose is frame 16, rotated by aim direction. (bodyset
        # is corpse decals, not the living player.)
        "player": {
            "sheet": "trooper.png", "grid": 8, "frame": 16, "pivot": [0.5, 0.5],
            "offset_deg": 0.0, "priority": PLAYER_PRIORITY,
        }
        if "trooper.png" in staged
        else None,
    }

    manifest_path = out_dir / "sprite_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"staged {len(staged)} sheets -> {out_dir}")
    print(f"wrote {manifest_path}")


if __name__ == "__main__":
    main()
