"""Bake extracted Crimsonland Classic sprites into the Godot project (M3).

Reads the PNG sheets produced by `crimson extract <game_dir> artifacts/assets`
and stages the ones the VR frontend renders into
`crimson-vr/godot/assets/sprites/` (gitignored — original art is never
committed, PLAN §10), alongside a JSON manifest describing how each entity type
maps to a sheet + frame. The manifest holds only factual layout metadata
(sheet name, grid, frame index, pivot), not asset-derived art.

Sheets are 8x8 grids (creature_render_type, src/crimson/creatures/anim.py). The
manifest carries each creature's animation layout (base_frame, mirror); the
renderer selects the live frame per instance from the snapshot's anim_phase +
flags (CreatureAnim.SelectFrame, slice 2). Orientation comes from the entity
heading, applied by the renderer. The player is still a single static torso
frame (leg animation needs a move-phase ABI field; deferred).

Usage:
    uv run crimson-vr/tools/bake_assets.py [assets_dir] [out_dir]
      assets_dir default: artifacts/assets
      out_dir     default: crimson-vr/godot/assets/sprites
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

# Repo root (…/crimson) so `import src.crimson…` works when the audio bake reads
# the reference sfx/weapon tables regardless of the caller's cwd.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Creature type_id -> sheet (src/crimson/creatures/spawn_ids.py CreatureTypeId).
CREATURE_SHEETS: dict[int, str] = {
    0: "zombie.png",
    1: "lizard.png",
    2: "alien.png",
    3: "spider_sp1.png",
    4: "spider_sp2.png",
    5: "trooper.png",
}
CREATURE_GRID = 8  # 8x8 atlas (creature_render_type)

# Per-type animation layout (src/crimson/sim/world_defs.py CREATURE_ANIM):
# base frame index + whether the long-strip walk cycle mirror-folds. The live
# anim_phase + runtime flags (both in the ABI snapshot) pick the actual frame at
# render time via CreatureAnim.SelectFrame (a port of creature_anim_select_frame).
# anim_rate is a sim-side quantity (it advances anim_phase) and is not needed by
# the frontend. type_id -> (base_frame, mirror).
CREATURE_ANIM: dict[int, tuple[int, bool]] = {
    0: (0x20, False),  # zombie
    1: (0x10, True),   # lizard
    2: (0x20, False),  # alien
    3: (0x10, True),   # spider_sp1
    4: (0x10, True),   # spider_sp2
    5: (0x00, False),  # trooper
}

# Draw-order priority per type (higher = drawn on top), matching the original's
# fixed creature draw order (_NATIVE_CREATURE_SPRITE_DRAW_ORDER, bottom->top):
# ZOMBIE, SPIDER_SP1, SPIDER_SP2, ALIEN, LIZARD. The game does no per-instance
# Y-sort; within a type it's pool order. Trooper isn't in the native list, so it
# gets a mid value.
CREATURE_PRIORITY: dict[int, int] = {
    0: 6,   # zombie (bottom)
    3: 7,   # spider_sp1
    4: 8,   # spider_sp2
    5: 9,   # trooper (not in native pass)
    2: 9,   # alien
    1: 10,  # lizard (top)
}
PLAYER_PRIORITY = 15  # above creatures, below projectiles/bonuses (native pass order)

# Sheets to stage: (source-relative-path, dest-name).
GAME = "crimson/game"


def main() -> None:
    assets_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("artifacts/assets")
    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("crimson-vr/godot/assets/sprites")
    out_dir.mkdir(parents=True, exist_ok=True)

    needed = set(CREATURE_SHEETS.values()) | {"bodyset.png", "projs.png", "bonuses.png"}
    staged: dict[str, list[int]] = {}
    for name in sorted(needed):
        src = assets_dir / GAME / name
        if not src.exists():
            print(f"WARN missing sheet: {src}")
            continue
        shutil.copy2(src, out_dir / name)
        # Record pixel size so the manifest is self-describing for the renderer.
        from PIL import Image

        with Image.open(src) as im:
            staged[name] = list(im.size)

    manifest = {
        "note": "Generated by crimson-vr/tools/bake_assets.py from user-supplied "
        "Crimsonland Classic assets. Layout metadata only; no art is committed.",
        "sheets": {
            name: {"size": size, "grid": CREATURE_GRID if name in CREATURE_SHEETS.values() else None}
            for name, size in staged.items()
        },
        # offset_deg corrects each sheet's baked art facing relative to the sim
        # heading. Creature sheets are drawn 90 deg CW of the trooper torso, so
        # rotate them -90 (validated in-headset against the debug needle).
        "creatures": {
            str(type_id): {
                "sheet": sheet, "grid": CREATURE_GRID,
                # frame is the static fallback (used only if animation is off or
                # the layer draws colored quads); base_frame + mirror drive the
                # animated per-instance frame selection.
                "frame": CREATURE_ANIM.get(type_id, (0, False))[0],
                "base_frame": CREATURE_ANIM.get(type_id, (0, False))[0],
                "mirror": CREATURE_ANIM.get(type_id, (0, False))[1],
                "pivot": [0.5, 0.5], "offset_deg": -90.0,
                "priority": CREATURE_PRIORITY.get(type_id, 8),
            }
            for type_id, sheet in CREATURE_SHEETS.items()
            if sheet in staged
        },
        # Player is drawn from trooper.png (8x8), same sheet as the trooper
        # creature (src/crimson/render/world/trooper.py). torso_frame = leg_frame
        # + 16; static torso pose is frame 16, rotated by aim direction. (bodyset
        # is corpse decals, not the living player.)
        "player": {
            "sheet": "trooper.png", "grid": 8, "frame": 16, "pivot": [0.5, 0.5],
            "offset_deg": 0.0, "priority": PLAYER_PRIORITY,
        }
        if "trooper.png" in staged
        else None,
    }

    manifest_path = out_dir / "sprite_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"staged {len(staged)} sheets -> {out_dir}")
    print(f"wrote {manifest_path}")

    # Audio lives beside the sprites (…/assets/audio) unless out_dir was given.
    audio_out = out_dir.parent / "audio" if out_dir.name == "sprites" else out_dir / "audio"
    stage_audio(assets_dir, audio_out)


def stage_audio(assets_dir: Path, out_dir: Path) -> None:
    """Stage the sfx Oggs + an audio manifest the frontend uses to route the
    host-ABI audio events (crimson_host_audio_events) to sounds.

    The ABI emits sfx events as `@intFromEnum(SfxId)`; the Zig SfxId enum order
    is identical to the Python SFX_NATIVE_ORDER (both derived from
    audio_init_sfx / sfx_load_sample load order), so a sound's native id is its
    index in that tuple. Shot/reload events carry a weapon_id, which we resolve
    to a fire/reload native id via the weapons table. No art/audio bytes are
    committed — only this factual routing metadata (PLAN §10).
    """
    from src.crimson.weapons import WEAPON_BY_ID, WeaponId
    from src.grim.sfx_map import SFX_NATIVE_ORDER, SFX_SPECS, SfxId

    out_dir.mkdir(parents=True, exist_ok=True)
    # native id (index) -> ogg filename, in enum order (index == ABI sfx id).
    sfx_files = [SFX_SPECS[sid].entry_name for sid in SFX_NATIVE_ORDER]
    idx = {sid.value: i for i, sid in enumerate(SFX_NATIVE_ORDER)}

    staged = 0
    for name in sorted(set(sfx_files)):
        src = assets_dir / "sfx" / name
        if not src.exists():
            print(f"WARN missing sfx: {src}")
            continue
        shutil.copy2(src, out_dir / name)
        staged += 1

    manifest = {
        "note": "Generated by crimson-vr/tools/bake_assets.py from user-supplied "
        "Crimsonland Classic assets. Routing metadata only; no audio is committed.",
        # index = native sfx id (ABI @intFromEnum(SfxId)); value = ogg filename.
        "sfx": sfx_files,
        # weapon_id -> native sfx id for its fire / reload sound (weapons table).
        "weapon_fire": {str(int(w)): idx[WEAPON_BY_ID[w].fire_sound.value] for w in WEAPON_BY_ID},
        "weapon_reload": {str(int(w)): idx[WEAPON_BY_ID[w].reload_sound.value] for w in WEAPON_BY_ID},
        # Fire-Bullets suppresses the per-weapon shot sfx and plays these two
        # instead (audio_router.handle_player_audio).
        "fire_bullets_weapon_id": int(WeaponId.FIRE_BULLETS),
        "plasma_minigun_weapon_id": int(WeaponId.PLASMA_MINIGUN),
        # Hit sfx: shock hits -> shock_hit; else one of the six bullet-hit
        # samples (the ABI supplies the resolved roll index).
        "bullet_hit": [idx[getattr(SfxId, f"BULLET_HIT_0{n}").value] for n in range(1, 7)],
        "shock_hit": idx[SfxId.SHOCK_HIT_01.value],
    }
    manifest_path = out_dir / "audio_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"staged {staged} sfx -> {out_dir}")
    print(f"wrote {manifest_path}")


if __name__ == "__main__":
    main()
