IMAGE=grim.dll
FUNCTION=d3dx_jpeg_process_data_crank_post
COMPILER=msvc7.0
SYMBOL=process_data_crank_post
SOURCE=../../../../third_party/sources/ijg-libjpeg-6a/jdmainct.c
NOTE=ijg-6a-d3dx-two-pass-postprocessor-dispatch
CFLAGS='/O1 /G6 /W3 /MD /DHAVE_BOOLEAN /Dboolean="unsigned char"'
